ALTER TABLE users
  ADD COLUMN IF NOT EXISTS avatar_url TEXT,
  ADD COLUMN IF NOT EXISTS notification_enabled BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS marketing_enabled BOOLEAN DEFAULT FALSE;
